FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
      iputils-ping \
      iproute2 \
      nginx \
      curl \
      telnet \
      nmap \
      ;

CMD ["/bin/bash"]

COPY Dockerfile.network_example /

# docker build --tag network_example -f ./Dockerfile.network_example .

