services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile.network_example
    image: network_example:latest
    pull_policy: build
    container_name: nodeA
    command: sleep infinity
    networks:
      my_custom_net:
        ipv4_address: 10.1.1.10
      secondary_net:
        ipv4_address: 10.2.2.10

  node2:
    image: network_example:latest
    container_name: nodeB
    command: sleep infinity
    depends_on:
      - node1
    networks:
      my_custom_net:
        ipv4_address: 10.1.1.20

  node3:
    image: network_example:latest
    container_name: nodeC
    command: sleep infinity
    depends_on:
      - node1
    networks:
      my_custom_net:
        ipv4_address: 10.1.1.30

  node4:
    image: network_example:latest
    container_name: nodeD
    command: sleep infinity
    depends_on:
      - node1
    networks:
      my_custom_net:
        ipv4_address: 10.1.1.40

networks:
  my_custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1

  secondary_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.2.0/24
          gateway: 10.2.2.1


